version: '2'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      PORT: 5000
      POSTGRESQL_DATABASE_URL: postgresql+psycopg2://user:password@172.16.239.3:5432/testdb
      LINEBOT_CHANNEL_ACCESS_TOKEN: gJhGY0QpKvarghG2IoTlqPzvV9c4mjn/QBBIJfnGqyBjq8PoT0nwvzsu+fu2NXiTLDlJgx3DAraCOZlKg0XJdj7cJkLOGVPRFra5CFPiFxF4ve7BNTKNFvFrs7ThEIJXPE5BHnxNl1fFbqOcoq5OLAdB04t89/1O/w1cDnyilFU=
      LINEBOT_CHANNEL_SECRET: f90c674400c11266b9e2ce5272288f9e
      LINE_PAY_URL: https://sandbox-api-pay.line.me
      LINE_PAY_CHANNEL_ID: 1651375995
      LINE_PAY_CHANNEL_SECRET: e1285ef1486a4a18c70f7e5a2bb959aa
      LINE_PAY_CONFIRM_URL: https://704bc7e2.ngrok.io/pay/confirm
      QUOTAGUARDSTATIC_URL: http://c1d5ikljkuvor4:s415QrLcMCxm8HqE8cK-Kg_F2Q@us-east-static-06.quotaguard.com:9293
    volumes:
      - ./app:/app
    networks:
      app_net:
        ipv4_address: 172.16.239.2
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    ports:
      - "5432:5432"
    tty: true
    restart: always
    volumes: # マウントの設定 ... ホスト側ディレクトリ:コンテナ側ディレクトリ
      - ./db/sh:/docker-entrypoint-initdb.d # この中の.sh、.sqlファイルは自動実行される
    networks:
      app_net:
        ipv4_address: 172.16.239.3

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.239.0/24
         gateway: 172.16.239.1
